apiVersion: v1
kind: Service
metadata:
  name: todopy
spec:
  type: NodePort
  selector:
    app: todopy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30001

      

