name: Docker CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  login-dockerhub:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Build the Docker image and push it to AWS ECR, building and pushing to ECR will be done from Runner instance, as it should for CI
        run: |
          echo "Change directory to where our code is."
          cd /home/ubuntu/actions-runner/_work/todo-list-dockerized/todo-list-dockerized

          echo "Login to ECR repository"
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 724772048392.dkr.ecr.us-east-1.amazonaws.com

          echo "Build Docker image"
          docker build -t image-repository .

          echo "Tag Docker"
          docker tag image-repository:latest 724772048392.dkr.ecr.us-east-1.amazonaws.com/image-repository:latest

          echo "Push Docker image to ECR"
          docker push 724772048392.dkr.ecr.us-east-1.amazonaws.com/image-repository:latest

      
      # - name: CD. Pull the image from ECR and Deploy the app on the deployment server
      #   run: |

      #     echo "pull the latest image from ecr"
      #     docker pull 724772048392.dkr.ecr.us-east-1.amazonaws.com/image-repository:latest

      #     echo "Stopping and removing the existing container if it's running"
      #     docker ps -q --filter "ancestor=724772048392.dkr.ecr.us-east-1.amazonaws.com/image-repository:latest" | xargs -r docker stop | xargs -r docker rm

      #     docker run -d -p 8000:8000 724772048392.dkr.ecr.us-east-1.amazonaws.com/image-repository:latest > /dev/null 2>&1 &
      #     echo "Access the application on http://18.212.130.140:8000"

      #     echo "Pruning unused Docker images"
      #     docker image prune -f
