name: CI/CD pipeline for a TO-DO application, written in python

on:
  push:
    branches:
      - main

jobs:
  login-ecr:
    runs-on: self-hosted

    steps:

      - name: Checkout code onto the runner instance, exists temporarily in ~/actions-runner/_work/
        uses: actions/checkout@v2

      - name: Set up AWS CLI, make sure AWS CLI is installed on runner instance, with docker 
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Build the Docker image and push it to AWS ECR, building and pushing to ECR will be done from Runner instance, as it should for CI
        run: |
          echo "Change directory to where our code is"
          cd /home/ec2-user/actions-runner/_work/todo-list-dockerized/todo-list-dockerized

          echo "Login to ECR repository"
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 724772048392.dkr.ecr.us-east-1.amazonaws.com

          echo "Build Docker image"
          docker build -t image-repository .

          echo "Tag Docker"
          docker tag image-repository:latest 724772048392.dkr.ecr.us-east-1.amazonaws.com/image-repository:latest

          echo "Push Docker image to ECR"
          docker push 724772048392.dkr.ecr.us-east-1.amazonaws.com/image-repository:latest

      
      - name: CD. Pull the image from ECR and Deploy the app on the deployment server, install docker and aws-cli and pre-run aws configure on deployment server 
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |

            echo "Login to ECR repository"
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 724772048392.dkr.ecr.us-east-1.amazonaws.com

            echo "pull the latest image from ecr"
            docker pull 724772048392.dkr.ecr.us-east-1.amazonaws.com/image-repository:latest


            docker run -d -p 8000:8000 724772048392.dkr.ecr.us-east-1.amazonaws.com/image-repository:latest # > /dev/null 2>&1 &
            
            echo "Access the application on http://3.140.188.18:8000"
